name: _
environment:
  sdk: ^3.6.1
workspace:
- package1
- package2
- app
dependencies:
  args: ^2.6.0
  freezed_annotation: ^2.4.4
  cupertino_icons: ^1.0.8
  phoenix_socket: 
    git:
      url: https://github.com/braverhealth/phoenix-socket-dart
      ref: 4c3f76476cb846c1bcf92272952162f52af25c86

dev_dependencies:
  flutter_lints: ^5.0.0
  lints: ^5.1.1
  build_runner: ^2.4.14
  freezed: ^2.5.8
