name: package1
description: A starting point for Dart libraries or applications.
version: 1.0.0

resolution: workspace
environment:
  sdk: ^3.6.0

dependencies:
  freezed_annotation:

dev_dependencies:
  build_runner:
  freezed:
  lints:
  test:
